# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
